# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_casa_polvora.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tela_casa_polvora(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1176, 748)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 150, 381, 291))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../imagens/foto12.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 440, 381, 251))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../imagens/foto11.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 0, 1151, 141))
        self.widget.setStyleSheet("background-color: rgb(255,222,173);")
        self.widget.setObjectName("widget")
        self.layoutWidget = QtWidgets.QWidget(self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(990, 20, 141, 100))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_sair = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_sair.setStyleSheet("background-color: rgb(92, 160, 212);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_sair.setObjectName("pushButton_sair")
        self.verticalLayout_3.addWidget(self.pushButton_sair)
        self.pushButton_voltar = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_voltar.setStyleSheet("background-color: rgb(92, 160, 212);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_voltar.setObjectName("pushButton_voltar")
        self.verticalLayout_3.addWidget(self.pushButton_voltar)
        self.pushButton_perfil = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_perfil.setStyleSheet("background-color: rgb(70, 0, 211);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_perfil.setObjectName("pushButton_perfil")
        self.verticalLayout_3.addWidget(self.pushButton_perfil)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(-10, -10, 341, 151))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../imagens/logo.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(680, 570, 231, 41))
        self.pushButton.setStyleSheet("background-color: rgb(92, 160, 212);\n"
"font: 9pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(410, 150, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(58, 0, 173);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(410, 200, 741, 121))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(560, 330, 451, 211))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgb(239, 239, 239);\n"
"color: rgb(85, 0, 127);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(560, 330, 121, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(92, 160, 212);\n"
"font: 9pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1176, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.label_3.setPixmap(QtGui.QPixmap("imagens/logo.png"))
        self.label.setPixmap(QtGui.QPixmap("imagens/foto12.jpg"))
        self.label_2.setPixmap(QtGui.QPixmap("imagens/foto11.jpg"))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_sair.setText(_translate("MainWindow", "SAIR"))
        self.pushButton_voltar.setText(_translate("MainWindow", "Voltar"))
        self.pushButton_perfil.setText(_translate("MainWindow", "Perfil"))
        self.pushButton.setText(_translate("MainWindow", "Reservar visita"))
        self.label_4.setText(_translate("MainWindow", "Casa da pólvora"))
        self.label_5.setText(_translate("MainWindow", "Conheça o museu mais antigo do Piauí. A Casa da Pólvora é uma construção de uma \n"
"única sala de pedras toscas e rejuntadas com argamassa de barro e representa o grande \n"
"momento militar do Piauí. Construção datada do início do século XIX para abrigar a fábrica \n"
"de pólvora, edificada sobre um único lajedo, às margens do riacho Pouca Vergonha é o \n"
"marco da emancipação do Piauí, durante as lutas pela independência.\n"
""))
        self.label_6.setText(_translate("MainWindow", "\n"
"                        Segunda a Sexta    |     Sábado \n"
"—------------------------------------------------------------------\n"
"Manhã                9h às 10h            |    9h às 10h\n"
"—-------------------------------------------------------------------\n"
"Tarde               16:30h às 17:30h    |          - \n"
""))
        self.label_7.setText(_translate("MainWindow", " Horários de visita "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_tela_casa_polvora()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
