# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_nota_fiscal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tela_nota_fiscal(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(832, 663)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 801, 21))
        self.widget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(430, 20, 761, 21))
        self.widget_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget_2.setObjectName("widget_2")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(10, 570, 791, 21))
        self.widget_3.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget_3.setObjectName("widget_3")
        self.widget_5 = QtWidgets.QWidget(self.widget_3)
        self.widget_5.setGeometry(QtCore.QRect(430, 20, 761, 21))
        self.widget_5.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget_5.setObjectName("widget_5")
        self.label_qrcode = QtWidgets.QLabel(self.centralwidget)
        self.label_qrcode.setGeometry(QtCore.QRect(10, 40, 461, 451))
        self.label_qrcode.setStyleSheet("border: 1px solid black;")
        self.label_qrcode.setText("")
        self.label_qrcode.setObjectName("label_qrcode")
        self.lineEdit_nome = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nome.setGeometry(QtCore.QRect(480, 50, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_nome.setFont(font)
        self.lineEdit_nome.setReadOnly(True)
        self.lineEdit_nome.setObjectName("lineEdit_nome")
        self.lineEdit_tipo = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_tipo.setGeometry(QtCore.QRect(480, 100, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_tipo.setFont(font)
        self.lineEdit_tipo.setReadOnly(True)
        self.lineEdit_tipo.setObjectName("lineEdit_tipo")
        self.lineEdit_data = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_data.setGeometry(QtCore.QRect(480, 150, 331, 31))
        self.lineEdit_data.setReadOnly(True)
        self.lineEdit_data.setObjectName("lineEdit_data")
        self.lineEdit_horario = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_horario.setGeometry(QtCore.QRect(480, 200, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_horario.setFont(font)
        self.lineEdit_horario.setReadOnly(True)
        self.lineEdit_horario.setObjectName("lineEdit_horario")
        self.lineEdit_valor = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_valor.setGeometry(QtCore.QRect(480, 250, 331, 31))
        self.lineEdit_valor.setReadOnly(True)
        self.lineEdit_valor.setObjectName("lineEdit_valor")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(640, 510, 161, 41))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(490, 290, 301, 171))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 510, 451, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 832, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Fechar"))
        self.label.setText(_translate("MainWindow", "Agradecemos sua escolha em explorar \n"
"nossa região. Sua presença não apenas \n"
"enriquece nossa comunidade, mas \n"
"também contribui para a preservação \n"
"e celebração da rica cultura e história \n"
"que tornam este destino tão especial. \n"
"Tenha uma estadia memorável! (●\'◡\'●)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_tela_nota_fiscal()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
